version: 2
jobs:
  build:
    working_directory: ~/angular-material-expander
    docker:
      - image: circleci/node:6-jessie-browsers
        environment:
          NODE_ENV: test
    steps:
      - checkout

      - run: npm install bower
      - run: npm install

      - run: npm rebuild node-sass

      - run: npm test
